// TypeScript Interface
interface CarBrands {
  [brand: string]: string[];
}

// Object of car brands and their models
export const carBrands: CarBrands = {
  Toyota: [
    "Camry",
    "Corolla",
    "RAV4",
    "Highlander",
    "Tacoma",
    "Tundra",
    "4Runner",
    "Prius",
    "Sienna",
    "Avalon",
    "Supra",
    "GR86",
  ],
  Honda: [
    "Accord",
    "Civic",
    "CR-V",
    "Pilot",
    "Odyssey",
    "HR-V",
    "Ridgeline",
    "Passport",
    "Fit",
    "Insight",
  ],
  Ford: [
    "F-150",
    "Mustang",
    "Explorer",
    "Escape",
    "Edge",
    "Bronco",
    "Ranger",
    "Expedition",
    "Maverick",
    "EcoSport",
  ],
  Chevrolet: [
    "Silverado",
    "Malibu",
    "Equinox",
    "Traverse",
    "Tahoe",
    "Suburban",
    "Colorado",
    "Blazer",
    "Corvette",
    "Camaro",
  ],
  BMW: [
    "3 Series",
    "5 Series",
    "7 Series",
    "X3",
    "X5",
    "X7",
    "i4",
    "iX",
    "M3",
    "M5",
    "Z4",
  ],
  Mercedes: [
    "C-Class",
    "E-Class",
    "S-Class",
    "GLA",
    "GLC",
    "GLE",
    "GLS",
    "A-Class",
    "CLA",
    "AMG GT",
  ],
  Audi: ["A3", "A4", "A6", "A8", "Q3", "Q5", "Q7", "Q8", "e-tron", "TT", "R8"],
  Tesla: ["Model 3", "Model S", "Model X", "Model Y", "Cybertruck"],
  Nissan: [
    "Altima",
    "Sentra",
    "Maxima",
    "Rogue",
    "Pathfinder",
    "Frontier",
    "Titan",
    "Armada",
    "Kicks",
    "Murano",
    "Z",
  ],
  Hyundai: [
    "Elantra",
    "Sonata",
    "Tucson",
    "Santa Fe",
    "Palisade",
    "Kona",
    "Venue",
    "Ioniq 5",
    "Genesis",
  ],
  Mazda: ["Mazda3", "Mazda6", "CX-5", "CX-9", "CX-30", "CX-50", "MX-5 Miata"],
  Subaru: [
    "Outback",
    "Forester",
    "Crosstrek",
    "Impreza",
    "Legacy",
    "Ascent",
    "WRX",
    "BRZ",
  ],
  Volkswagen: [
    "Jetta",
    "Passat",
    "Tiguan",
    "Atlas",
    "Golf",
    "GTI",
    "ID.4",
    "Taos",
    "Arteon",
  ],
  Jeep: [
    "Wrangler",
    "Grand Cherokee",
    "Cherokee",
    "Compass",
    "Renegade",
    "Gladiator",
    "Wagoneer",
    "Grand Wagoneer",
  ],
  Lexus: ["ES", "IS", "LS", "RX", "NX", "GX", "LX", "UX", "LC"],
  Porsche: [
    "911",
    "Cayenne",
    "Macan",
    "Panamera",
    "Taycan",
    "718 Boxster",
    "718 Cayman",
  ],
  Kia: [
    "Forte",
    "K5",
    "Stinger",
    "Soul",
    "Sportage",
    "Sorento",
    "Telluride",
    "Carnival",
    "EV6",
    "Niro",
  ],
  Dodge: ["Charger", "Challenger", "Durango", "Hornet"],
  Ram: ["1500", "2500", "3500", "ProMaster"],
  GMC: ["Sierra", "Canyon", "Yukon", "Acadia", "Terrain", "Hummer EV"],
  Acura: ["ILX", "TLX", "MDX", "RDX", "Integra", "NSX"],
};
